
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author bean_
 */
public class ActualizarTripulacion extends javax.swing.JFrame {

    /**
     * Creates new form PiratasTripulacion
     */
    public ActualizarTripulacion() {
        initComponents();
        
          setSize(1000,565);
        setResizable(false); //con este metodo evitamos que el usuario modifique la dimensiones de la ventana
        setTitle("Piratas con Tripulacion");
        setLocationRelativeTo(null);
        
        ImageIcon background = new ImageIcon("src/imagenes/bgTripulacion.png");
        Icon icono = new ImageIcon(background.getImage().getScaledInstance(lbBackground.getWidth(), lbBackground.getHeight(), Image.SCALE_DEFAULT));
        lbBackground.setIcon(icono);
        this.repaint(); //esta linea es para confirmar que se vea el jLabel de fondo
        
        
        //Imagen para icono
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image lcono_pantalla = toolkit.getImage("src/imagenes/icono.png");
        setIconImage(lcono_pantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttActualizar = new javax.swing.JButton();
        bttRegresar = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        lbIDPirata1 = new javax.swing.JLabel();
        txtIdPirata1 = new javax.swing.JTextField();
        lbIDPirata2 = new javax.swing.JLabel();
        txtIdPirata2 = new javax.swing.JTextField();
        txtIdPirata = new javax.swing.JTextField();
        lbIDPirata = new javax.swing.JLabel();
        lbAnimacion = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttActualizar.setBackground(new java.awt.Color(255, 204, 102));
        bttActualizar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        bttActualizar.setText("Actualizar");
        getContentPane().add(bttActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        bttRegresar.setBackground(new java.awt.Color(255, 204, 102));
        bttRegresar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        bttRegresar.setText("Regresar");
        bttRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(bttRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 120, 30));

        bttBuscar.setBackground(new java.awt.Color(255, 204, 102));
        bttBuscar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        bttBuscar.setText("Buscar");
        getContentPane().add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, 30));

        lbIDPirata1.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lbIDPirata1.setText("Barco:");
        getContentPane().add(lbIDPirata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 50, 30));

        txtIdPirata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPirata1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdPirata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 210, 30));

        lbIDPirata2.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lbIDPirata2.setText("Nombre:");
        getContentPane().add(lbIDPirata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 70, 30));

        txtIdPirata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPirata2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdPirata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 30));

        txtIdPirata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPirataActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdPirata, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, 30));

        lbIDPirata.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lbIDPirata.setText("IdTripulación:");
        getContentPane().add(lbIDPirata, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 120, 30));

        lbAnimacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gfPiratasT.gif"))); // NOI18N
        getContentPane().add(lbAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 330, 310));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgATripulacion.png"))); // NOI18N
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPirataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPirataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPirataActionPerformed

    private void bttRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttRegresarMouseClicked
        // TODO add your handling code here:
        Actualizaciones act = new Actualizaciones();
        act.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttRegresarMouseClicked

    private void txtIdPirata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPirata1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPirata1ActionPerformed

    private void txtIdPirata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPirata2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPirata2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarTripulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttActualizar;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttRegresar;
    private javax.swing.JLabel lbAnimacion;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbIDPirata;
    private javax.swing.JLabel lbIDPirata1;
    private javax.swing.JLabel lbIDPirata2;
    private javax.swing.JTextField txtIdPirata;
    private javax.swing.JTextField txtIdPirata1;
    private javax.swing.JTextField txtIdPirata2;
    // End of variables declaration//GEN-END:variables
}
