/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;



/**
 *
 * @author bean_
 */
public class ConsultaTripulacion extends javax.swing.JFrame {
    
    /**
     * Creates new form ConsultaTripulacion
     */
    public ConsultaTripulacion() {
        initComponents();
        
           setSize(1000,565);
        setResizable(false); //con este metodo evitamos que el usuario modifique la dimensiones de la ventana
        setTitle("Consulta de Tripulacion");
        setLocationRelativeTo(null);
        
        ImageIcon background = new ImageIcon("src/imagenes/bgCTripulacion.png");
        Icon icono = new ImageIcon(background.getImage().getScaledInstance(lbBackground.getWidth(), lbBackground.getHeight(), Image.SCALE_DEFAULT));
        lbBackground.setIcon(icono);
        this.repaint(); //esta linea es para confirmar que se vea el jLabel de fondo
        
        //Imagen para icono
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image lcono_pantalla = toolkit.getImage("src/imagenes/icono.png");
        setIconImage(lcono_pantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        bttBuscar = new javax.swing.JButton();
        bttRegresar = new javax.swing.JButton();
        lbAnimacion = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PIRATAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 410, 210));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 120, 30));

        lbNombre.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 410, 30));

        lbID.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lbID.setText("IDTripulacion:");
        getContentPane().add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 110, 30));

        bttBuscar.setBackground(new java.awt.Color(255, 102, 0));
        bttBuscar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        bttBuscar.setText("Buscar");
        bttBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 120, 30));

        bttRegresar.setBackground(new java.awt.Color(255, 102, 0));
        bttRegresar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        bttRegresar.setText("Regresar");
        bttRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(bttRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 120, 30));

        lbAnimacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgCTripulacion.gif"))); // NOI18N
        getContentPane().add(lbAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 210, 290));

        lbFondo.setBackground(new java.awt.Color(255, 102, 0));
        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgCTripulacion.png"))); // NOI18N
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttRegresarMouseClicked
        // TODO add your handling code here:
        Consultas con = new Consultas();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttRegresarMouseClicked

    private void bttBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttBuscarMouseClicked

    }//GEN-LAST:event_bttBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaTripulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAnimacion;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
