/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author bean_
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
           setSize(1000,565);
        setResizable(false); //con este metodo evitamos que el usuario modifique la dimensiones de la ventana
        setTitle("Inicio");
        setLocationRelativeTo(null);
        
        ImageIcon background = new ImageIcon("src/imagenes/bgInicio.png");
        Icon icono = new ImageIcon(background.getImage().getScaledInstance(lbBackground.getWidth(), lbBackground.getHeight(), Image.SCALE_DEFAULT));
        lbBackground.setIcon(icono);
        this.repaint(); //esta linea es para confirmar que se vea el jLabel de fondo
        
        //Imagen para icono
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image lcono_pantalla = toolkit.getImage("src/imagenes/icono.png");
        setIconImage(lcono_pantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttActualizar = new javax.swing.JButton();
        bttConsultas = new javax.swing.JButton();
        bttReportes = new javax.swing.JButton();
        bttSalir = new javax.swing.JButton();
        lbAnimacion2 = new javax.swing.JLabel();
        lbAnimacion = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bttActualizacion.png"))); // NOI18N
        bttActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttActualizarMouseClicked(evt);
            }
        });
        getContentPane().add(bttActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 120, 110));

        bttConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bttConsultas.png"))); // NOI18N
        bttConsultas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttConsultasMouseClicked(evt);
            }
        });
        getContentPane().add(bttConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 120, 110));

        bttReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bttReportes.png"))); // NOI18N
        bttReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttReportesMouseClicked(evt);
            }
        });
        getContentPane().add(bttReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 120, 110));

        bttSalir.setBackground(new java.awt.Color(255, 51, 51));
        bttSalir.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        bttSalir.setText("Salir");
        bttSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bttSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 160, 40));

        lbAnimacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gfInicio2.gif"))); // NOI18N
        getContentPane().add(lbAnimacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 350, 280));

        lbAnimacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gfInicio.gif"))); // NOI18N
        getContentPane().add(lbAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 160, 360, 410));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgInicio.png"))); // NOI18N
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 570));
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttActualizarMouseClicked
        // TODO add your handling code here:
        Actualizaciones act = new Actualizaciones(); //Hacemos una nueva instancia de la ventana a llamar
        act.setVisible(true);
        this.dispose(); //este metodo es para que cuando se abra la otra ventana, se cierre esta
    }//GEN-LAST:event_bttActualizarMouseClicked

    private void bttSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bttSalirActionPerformed

    private void bttConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttConsultasMouseClicked
        // TODO add your handling code here:
        Consultas con = new Consultas();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttConsultasMouseClicked

    private void bttReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttReportesMouseClicked
        // TODO add your handling code here:
        Reportes rep = new Reportes();
        rep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttReportesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttActualizar;
    private javax.swing.JButton bttConsultas;
    private javax.swing.JButton bttReportes;
    private javax.swing.JButton bttSalir;
    private javax.swing.JLabel lbAnimacion;
    private javax.swing.JLabel lbAnimacion2;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbFondo;
    // End of variables declaration//GEN-END:variables
}
