/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author bean_
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
              
        setSize(400,450);
        setResizable(false); //con este metodo evitamos que el usuario modifique la dimensiones de la ventana
        setTitle("Login");
        setLocationRelativeTo(null);
        
        ImageIcon background = new ImageIcon("src/imagenes/bgLogin.png");
        Icon icono = new ImageIcon(background.getImage().getScaledInstance(lbBackground.getWidth(), lbBackground.getHeight(), Image.SCALE_DEFAULT));
        lbBackground.setIcon(icono);
        this.repaint(); //esta linea es para confirmar que se vea el jLabel de fondo
        
        //Imagen para icono
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image lcono_pantalla = toolkit.getImage("src/imagenes/icono.png");
        setIconImage(lcono_pantalla);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lbUsuario = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttIngresar.setBackground(new java.awt.Color(255, 204, 51));
        bttIngresar.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        bttIngresar.setText("INGRESAR");
        bttIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttIngresarMouseClicked(evt);
            }
        });
        getContentPane().add(bttIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, 40));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 170, 30));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 170, 30));

        lbUsuario.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        lbUsuario.setText("USUARIO:");
        getContentPane().add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        lbPassword.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        lbPassword.setText("CONTRASEÑA:");
        getContentPane().add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgLogin.png"))); // NOI18N
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttIngresarMouseClicked
        // TODO add your handling code here:
        String usuario = new String("bean");
        String password = new String("carolina77");
        
        String user = txtUsuario.getText();
        String pass = txtPassword.getText();
        
        if(txtUsuario.getText().isEmpty() || txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Favor de ingresar usuario y contraseña");
        }else{
            try{
            if(usuario.equals(user) && password.equals(pass))
            {
                JOptionPane.showMessageDialog(null, "Bienvenido");
                
                Inicio ini = new Inicio();
                ini.setVisible(true);
                this.dispose();                
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrectos");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
      }
    }//GEN-LAST:event_bttIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Login lg = new Login();
        lg.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttIngresar;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
