/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bean_
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
        
           setSize(500,330);
        setResizable(false); //con este metodo evitamos que el usuario modifique la dimensiones de la ventana
        setTitle("Cargando");
        setLocationRelativeTo(null);
        
        ImageIcon background = new ImageIcon("src/imagenes/bgSplash.png");
        Icon icono = new ImageIcon(background.getImage().getScaledInstance(lbBackground.getWidth(), lbBackground.getHeight(), Image.SCALE_DEFAULT));
        lbBackground.setIcon(icono);
        this.repaint(); //esta linea es para confirmar que se vea el jLabel de fondo
        
        //Imagen para icono
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image lcono_pantalla = toolkit.getImage("src/imagenes/icono.png");
        setIconImage(lcono_pantalla);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAnimacion = new javax.swing.JLabel();
        lbTextCargando = new javax.swing.JLabel();
        lbPorcentaje = new javax.swing.JLabel();
        pbBarraCarga = new javax.swing.JProgressBar();
        lbFondo = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAnimacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gfLuffy.gif"))); // NOI18N
        getContentPane().add(lbAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -10, 240, 250));

        lbTextCargando.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        lbTextCargando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbTextCargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 250, 30));

        lbPorcentaje.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lbPorcentaje.setText("0");
        getContentPane().add(lbPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 234, 70, 30));
        getContentPane().add(pbBarraCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 250, 20));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgSplash.png"))); // NOI18N
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        splash vs = new splash();
        vs.setVisible(true);
        
        try {
            for(int i = 0; i <= 100; i++){
                Thread.sleep(70);
                vs.lbPorcentaje.setText(i +"%");
                
               if(i == 10){
                   vs.lbTextCargando.setText("Cargando los modulos...");
               }
               if(i == 25){
                   vs.lbTextCargando.setText("Cargando los modulos...");
               }
               if(i == 50){
                   vs.lbTextCargando.setText("Conectando a la base de datos...");
               }
               if(i == 75){
                   vs.lbTextCargando.setText("Coneccion exitosa...");
               }
                if (i == 90) {
                    vs.lbTextCargando.setText("Preparando los ultimos detalles");
                }
                vs.pbBarraCarga.setValue(i);
                if (i == 100){
                     vs.dispose();
                     Login lg = new Login();
                     lg.setVisible(true);    
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAnimacion;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbPorcentaje;
    private javax.swing.JLabel lbTextCargando;
    private javax.swing.JProgressBar pbBarraCarga;
    // End of variables declaration//GEN-END:variables
}
